site_name: 计算机教程

site_url: https://Muhamia.github.io/computer-tutorials/

theme:
  name: material

nav:

  - 首页: index.md

  - 计算机基本素养:
    - computer-basics/index.md
    # 下方是子部分的示例
    #- 开关机: 01-computer-basics/01-turn-computer-on-and-off.md
    #- 文件操作: 01-computer-basics/02-file-operations.md

  - C 语言入门:
    - programming-language-c/index.md

  - C++ 语言入门:
    - programming-language-cpp/index.md
