site_name: 计算机教程

site_url: https://Muhamia.github.io/computer-tutorials/

theme:
  name: material

nav:

  - 首页: index.md

  - 计算机基本素养:
    - computer-basics/index.md
    - 1.1 章:
      - 如何开机与关机: computer-basics/1.1/1.1.1/HowToSwitchOn.md
      - 键盘、鼠标、显示器: computer-basics/1.1/1.1.2/KeyBoardAndMouse.md
      - 电源: computer-basics/1.1/1.1.3/Power.md
      - CPU和GPU: computer-basics/1.1/1.1.45/CPUGPU.md
      - 内存和硬盘 存储单位: computer-basics/1.1/1.1.45/Memory.md
    - 1.2 章:
      - 压缩与解压: computer-basics/1.2/conpress.md
      - 文件拓展名: computer-basics/1.2/FileExtension.md
      - 路径: computer-basics/1.2/route.md
    - 1.3 章:
      - 关于杀毒软件: computer-basics/1.3/AntiVirus.md
      - 如何删除软件: computer-basics/1.3/delete.md
      - 如何找到正确的软件: computer-basics/1.3/search.md
      - 下载与安装: computer-basics/1.3/setup.md
    - 1.4 章:
      - 防火墙: computer-basics/1.4/firewall.md
      - 中国国家防火墙: computer-basics/1.4/GFW.md
    - 1.5 章:
      - 操作系统(OS): computer-basics/1.5/OS.md
      - 必要的系统设置: computer-basics/1.5/settings.md

  - C 语言入门:
    - programming-language-c/index.md

  - C++ 语言入门:
    - programming-language-cpp/index.md
